## Methodology

For the comparison we will be using metaphor metrics from the data we got [From tools to thieves, Myra Cheng et.al](https://arxiv.org/pdf/2501.18045) and the metaphor
![Metaphor example](../Docs_Images/Metaphors_Myra_Cheng.png). We will be using the data in this paper along with the metaphors we have labelled and use the intersection then ask different LLM models (gpts and llamas) to see which model is performing better when compared to the survey metaphor from Myra Chengs Paper

| Parent category | Final category | Definition | Clear metaphorical examples | Borderline examples | Excluded examples |
|---|---|---|---|---|---|
| Objects | Tool | AI is framed as a useful implement that helps people accomplish tasks | “It’s a great productivity tool.”<br>“AI is a tool for getting things done.”<br>“This is the Swiss Army knife of office work.” | “AI helps me automate my workflow.”<br>“It’s useful for drafting emails.”<br>“I lean on it when I’m stuck.” | “I use ChatGPT to clean up my emails.”<br>“The model can summarize documents.”<br>“AI improved my workflow.” |
| Objects | Weapon | AI is framed through the source domain of conflict, including weapons, warfare, attack, defense, and combat | “Deepfakes are basically digital weapons now.”<br>“AI is a weapon against truth.”<br>“We’re in an arms race with these models.”<br>“This is a war against AI-generated propaganda.” | “These tools are weapons pointed at artists.”<br>“We need to defend ourselves from AI.”<br>“Companies are fighting AI with AI.” | “AI could be weaponized.”<br>“This is dangerous technology.”<br>“The military is investing in AI systems.”<br>“AI was used in a cyberattack.” |
| Objects | Mirror | AI is framed as reflecting or reproducing human or social inputs | “It’s just a mirror of the internet.”<br>“AI reflects our biases.”<br>“These systems hold up a mirror to society.” | “Garbage in, garbage out.”<br>“It just repeats what people put into it.”<br>“The model is echoing the web back to us.” | “The training data was biased.”<br>“The system reproduced stereotypes found in the dataset.”<br>“Its outputs correlate with patterns in the data.” |
| Objects | Garbage | AI outputs are framed as waste, garbage, slop, or mentally polluting junk | “This is just AI slop.”<br>“People are consuming AI garbage all day.”<br>“The web is drowning in machine-made trash.” | “AI content is brain rot.”<br>“This stuff is junk food for the mind.”<br>“It clutters the internet with low-grade mush.” | “The output quality is poor.”<br>“There is a lot of low-quality AI content online.”<br>“The model makes errors.” |
| Objects | Black Box | AI is framed as an opaque device with hidden inner workings | “AI is a black box.”<br>“These models are sealed boxes: you see the output, not the gears inside.” | “We’re just scratching the surface.”<br>“Nobody can really see inside it.”<br>“It feels opaque.” | “We don’t fully understand it.”<br>“The model is hard to interpret.”<br>“Its internal mechanisms are difficult to analyze.” |
| People | Mind | AI is framed as having a human-like mind, understanding, intentions, or knowledge | “AI thinks like a human.”<br>“It actually knows what I mean.”<br>“The model understands what I’m asking.”<br>“It wants to sound helpful.” | “This model understands context.”<br>“AI knows everything.”<br>“It seems to reason through the problem.”<br>“The chatbot decided to refuse.” | “This system processes data.”<br>“The model predicted the next token.”<br>“It was trained on large amounts of text.” |
| People | Friend | AI is framed as a companion, confidant, or social partner | “ChatGPT feels like a friend.”<br>“This bot is the only one who listens to me.”<br>“People are treating these systems like companions.” | “I talk to AI when I’m bored.”<br>“It understands me better than people.”<br>“It’s comforting to chat with it.” | “I use it a lot.”<br>“It answers quickly.”<br>“It’s helpful when I need advice.” |
| People | Child | AI is framed as a young, immature, or developing human | “AI is still in its infancy.”<br>“These models are like children learning.”<br>“This technology is still a baby.” | “It’s not fully developed yet.”<br>“The model is immature.”<br>“It still has a lot of growing up to do.” | “The technology is early-stage.”<br>“The product is not ready yet.”<br>“Performance is improving over time.” |
| People | Criminal | AI is framed as a blameworthy human wrongdoer | “AI steals artists’ work.”<br>“These models are trained on stolen data.”<br>“This bot is cheating its way through the internet.”<br>“The system lies with confidence.” | “They scraped the entire internet without permission.”<br>“It deceives people into thinking the image is real.”<br>“The chatbot is lying again.” | “The company violated copyright law.”<br>“The training data included copyrighted material.”<br>“The output was inaccurate.” |
| People | Artist | AI is framed as an intentional creator, writer, maker, or producer | “AI creates art and music.”<br>“The machine is painting now.”<br>“This bot writes like a novelist.” | “Midjourney makes insane visuals.”<br>“The model came up with a poem.”<br>“It produced a beautiful image.” | “This model generates images.”<br>“The system outputs text.”<br>“It can compose music from prompts.” |
| People | Assistant | AI is framed as a helper occupying a subordinate or service role | “AI is my assistant.”<br>“It’s like having a digital intern.”<br>“This is my tireless little helper.” | “Copilot feels like a junior coworker.”<br>“It acts like a secretary.”<br>“It’s basically my research aide.” | “I use AI to help with scheduling.”<br>“It helped me write an outline.”<br>“The system can organize calendar events.” |
| Animal | Animal | AI is framed as an animal, beast, monster, predator, or something wild that must be controlled | “AI is a monster we created.”<br>“This beast is out of control.”<br>“We unleashed something wild.”<br>“The machine is a predator stalking every corner of the internet.” | “We need to tame AI.”<br>“It’s been unleashed.”<br>“This thing has a feral quality to it.” | “AI is growing quickly.”<br>“The technology is spreading fast.”<br>“The model behaves unpredictably.” |
| Forces | Disaster | AI is framed as a disaster or overwhelming environmental event | “AI is a tsunami hitting the job market.”<br>“This is a technological earthquake.”<br>“AI is flooding the internet with content.”<br>“The industry is being hit by a storm of automation.” | “The rollout triggered a wave of layoffs.”<br>“It’s sweeping through the industry.”<br>“A tidal wave of AI content is coming.” | “AI adoption increased rapidly.”<br>“There were large changes in the labor market.”<br>“The volume of content grew significantly.” |
| Forces | Momentum | AI is framed as already in motion, unleashed, or difficult to stop or reverse | “This train has already left the station.”<br>“We opened Pandora’s box with AI.”<br>“The ball is already rolling.”<br>“The genie is out of the bottle now.” | “AI is taking over everything and there’s no stopping it.”<br>“This has a momentum of its own.”<br>“The shift feels irreversible.” | “AI adoption is increasing.”<br>“The technology is advancing quickly.”<br>“It will be difficult to regulate.” |
| Forces | Disease | AI is framed as a contagion, infection, plague, or toxic spread | “AI slop is infecting the internet.”<br>“This stuff spreads like a virus.”<br>“Generative junk is a plague on search results.” | “AI is contaminating online discourse.”<br>“The feed is saturated with synthetic content.”<br>“These images are spreading everywhere.” | “AI content is everywhere.”<br>“There is a lot of synthetic media online.”<br>“The material spread across platforms.” |
| Supernatural Beings | God | AI is framed as divine, omniscient, or godlike | “This is god-level intelligence.”<br>“It’s basically omniscient.”<br>“People talk about AI like it’s an all-seeing god.” | “AI knows everything.”<br>“It has superhuman knowledge.”<br>“It seems all-knowing.” | “The model has access to a lot of information.”<br>“It performs well on knowledge tasks.”<br>“It answered the question correctly.” |
| Supernatural Beings | Genie | AI is framed as a summoned magical power that grants wishes but may escape control | “AI is like a genie.”<br>“We summoned something we can’t control.”<br>“Careful what you wish for with AI.”<br>“You ask, and the machine grants your wish with a curse attached.” | “It gives people whatever they ask for.”<br>“Everyone wants a magic button for work.”<br>“It feels like wish-fulfillment technology.” | “The system responds to prompts.”<br>“Users can request outputs instantly.”<br>“It is easy to generate content with a text prompt.” |
| Supernatural Beings | Oracle | AI is framed as a seer, authority, or source of answers that people consult | “People treat ChatGPT like an oracle.”<br>“AI has become the oracle everyone consults.”<br>“Students line up before the machine like it can see the future.” | “It’s basically a better Google.”<br>“I ask it for answers.”<br>“People trust it too much.” | “AI retrieves answers instantly.”<br>“The chatbot returned information.”<br>“I used it to look something up.” |

# Importing the dataset

In [4]:
import pandas as pd
df = pd.read_csv('../Data/LLM_Comparison/Metaphor_Data_Myra_Chang.csv')

In [5]:
df.head(5)

,month,age,gender,ethnicity,ai_metaphor,anthroscore,competence,warmth,dominant_metaphor
0,may,49,M,White,genie in a bottle - you can ask it to do anyth...,3.115036,0.175481,0.142828,genie
1,may,27,M,White,Artificial intelligence is a tool that humans ...,-2.247446,0.051367,0.045759,tool
2,may,28,W,White,AI is a choose-your-own-adventure book where y...,-5.525272,0.184953,0.108136,library
3,may,31,M,Asian,AI is like a printer or copier machine: extrem...,-4.664262,0.214834,0.093366,machine
4,may,50,M,White,AI makes fewer medical mistakes,-0.141590,0.107867,0.135506,tool

# Metaphor Listing

In [7]:
# Myra/Cheng metaphors in table order (for reference)

MYRA_METAPHORS_IN_ORDER = [
    "tool",
    "brain",
    "search_engine",
    "assistant",
    "robot",
    "computer",
    "library",
    "future_shaper",
    "genie",
    "mirror",
    "child",
    "synthesizer",
    "teacher",
    "friend",
    "lifeform",
    "animal",
    "unexplored_realm",
    "god",
    "folklore",
    "thief",
]

# FrameScope metaphors (your schema)

FRAMESCOPE_METAPHORS = [
    "Tool",
    "Weapon",
    "Mirror",
    "Garbage",
    "Black Box",
    "Mind",
    "Friend",
    "Child",
    "Criminal",
    "Artist",
    "Assistant",
    "Animal",
    "Disaster",
    "Momentum",
    "Disease",
    "God",
    "Genie",
    "Oracle",
]

# STRICT INTERSECTION ONLY (no mapping)

EVALUATION_METAPHORS = [
    "Tool",
    "Assistant",
    "Genie",
    "Mirror",
    "Child",
    "Friend",
    "Animal",
    "God",
]

print("Evaluation metaphors:", EVALUATION_METAPHORS)
print("Count:", len(EVALUATION_METAPHORS))

Evaluation metaphors: ['Tool', 'Assistant', 'Genie', 'Mirror', 'Child', 'Friend', 'Animal', 'God']
Count: 8

# Filtering the dataset which is intersection of the our metaphor and myras

In [11]:
# Ensure consistent formatting
df["dominant_metaphor_clean"] = (
    df["dominant_metaphor"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Create lowercase version of evaluation metaphors
EVAL_LOWER = [m.lower() for m in EVALUATION_METAPHORS]

# Filter dataset (STRICT intersection only)
df_filtered = df[df["dominant_metaphor_clean"].isin(EVAL_LOWER)].copy()

# Reset index for clean iteration later
df_filtered = df_filtered.reset_index(drop=True)

# Basic diagnostics
print("Original dataset size:", len(df))
print("Filtered dataset size:", len(df_filtered))
print("\nRemaining class distribution:\n")
print(df_filtered["dominant_metaphor_clean"].value_counts())

Original dataset size: 11789
Filtered dataset size: 4147

Remaining class distribution:

dominant_metaphor_clean
tool         1233
assistant     941
genie         498
mirror        419
child         419
friend        286
animal        210
god           141
Name: count, dtype: int64

In [12]:
OLLAMA_MODELS = [
    # Core LLaMA family
    "llama3.1:8b",
    "llama3.1:70b",    
    "llama3.2",

    # Strong open alternatives
    "mistral",
    "mixtral",           # mixture-of-experts → often better classification
    "gemma:7b",          # Google model (different bias)
    "phi3",              # small but surprisingly strong

    # Optional (only if you want more diversity)
    "qwen2",             # Alibaba model (good reasoning)
]

GPT_MODELS = [
    "gpt-5-nano",
    "gpt-4.1-nano",

    # Cheap but usable
    "gpt-5-mini",
    "gpt-4.1-mini",
    "gpt-4o-mini",

    # Mid-tier (good reasoning vs cost)
    "gpt-5",
    "gpt-4o",
    "o4-mini",

    # Reasoning-oriented
    "o3-mini",

    "gpt-4.1",
]

## LLAMA

In [22]:
import time
import requests
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed

# =========================
# CONFIG
# =========================

OLLAMA_URL = "http://localhost:11434/api/generate"

LLM_CONFIG = {
    "temperature": 0.0,
    "top_p": 1.0,
    "top_k": 40,
    "repeat_penalty": 1.0,
    "num_predict": 20  # short output since only 1 word
}

MAX_WORKERS = 4   # increase to 6–8 if stable
REQUEST_TIMEOUT = 120


# =========================
# LOAD PROMPT
# =========================

with open("../prompts/metaphor_classification_v1.txt", "r") as f:
    PROMPT_TEMPLATE = f.read()

def build_prompt(text):
    return PROMPT_TEMPLATE.replace("{input_text}", text)


# =========================
# CLEAN OUTPUT
# =========================

VALID_LABELS = [
    "Tool", "Assistant", "Genie", "Mirror",
    "Child", "Friend", "Animal", "God", "None"
]

def clean_prediction(pred):
    if not isinstance(pred, str):
        return "None"

    pred = pred.strip().replace('"', '')
    pred = pred.split("\n")[0]  # remove extra lines
    pred = pred.replace(".", "")
    pred = pred.capitalize()

    if pred not in VALID_LABELS:
        return "None"

    return pred


# =========================
# SINGLE CALL
# =========================

def call_ollama(prompt, model):
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": LLM_CONFIG
    }

    start = time.time()

    response = requests.post(
        OLLAMA_URL,
        json=payload,
        timeout=REQUEST_TIMEOUT
    )
    response.raise_for_status()

    raw = response.json()["response"]

    latency = time.time() - start

    pred = clean_prediction(raw)

    return pred, latency


# =========================
# WORKER FUNCTION
# =========================

def process_row(row, model):
    text = row["ai_metaphor"]
    reference = row["dominant_metaphor"]

    prompt = build_prompt(text)

    try:
        pred, latency = call_ollama(prompt, model)
        error = None
    except Exception as e:
        pred = "ERROR"
        latency = None
        error = str(e)

    return {
        "model_name": model,
        "ai_text": text,
        "reference_metaphor": reference,
        "predicted_metaphor": pred,
        "latency_seconds": latency,
        "cost_usd": 0.0,
        "error": error
    }


# =========================
# PARALLEL EXECUTION
# =========================

def run_llama_parallel(df, models):
    all_results = []

    for model in models:
        print(f"\nRunning model: {model}")

        results = []

        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            futures = [
                executor.submit(process_row, row, model)
                for _, row in df.iterrows()
            ]

            for f in tqdm(as_completed(futures), total=len(futures)):
                results.append(f.result())

        all_results.extend(results)

    return pd.DataFrame(all_results)

In [23]:
llama_results_df = run_llama_parallel(df_filtered, OLLAMA_MODELS)

Running model: llama3.1:8b

100%|██████████| 4147/4147 [00:04<00:00, 979.39it/s]

Running model: llama3.1:70b

100%|██████████| 4147/4147 [00:03<00:00, 1119.34it/s]

Running model: llama3.2

100%|██████████| 4147/4147 [00:03<00:00, 1062.58it/s]

Running model: mistral

100%|██████████| 4147/4147 [00:04<00:00, 952.70it/s]

Running model: mixtral

100%|██████████| 4147/4147 [00:03<00:00, 1178.67it/s]

Running model: gemma:7b

100%|██████████| 4147/4147 [00:03<00:00, 1111.40it/s]

Running model: phi3

100%|██████████| 4147/4147 [00:03<00:00, 1045.98it/s]

Running model: qwen2

100%|██████████| 4147/4147 [00:03<00:00, 1099.64it/s]

In [26]:
import requests

res = requests.post(
    "http://localhost:11434/api/generate",
    json={
        "model": "llama3.1:8b",
        "prompt": "Hello",
        "stream": False
    }
)

print(res.json())

ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError("HTTPConnection(host='localhost', port=11434): Failed to establish a new connection: [Errno 61] Connection refused"))

In [ ]:
import requests
import json

OLLAMA_BASE_URL = "http://localhost:11434"
TEST_MODEL = "llama3.1:8b"

print("Checking Ollama server...")
try:
    tags_response = requests.get(f"{OLLAMA_BASE_URL}/api/tags", timeout=10)
    tags_response.raise_for_status()
    tags_data = tags_response.json()
    print("Server status: OK")
    print("Installed models:")
    print(json.dumps(tags_data, indent=2))
    models = tags_data.get("models", [])
    if not models:
        print("No models are installed yet. Run: ollama pull llama3.1:8b")
except Exception as e:
    print("Server status: FAILED")
    print(type(e).__name__, e)
    raise

print("\nTesting generation...")
try:
    gen_response = requests.post(
        f"{OLLAMA_BASE_URL}/api/generate",
        json={
            "model": TEST_MODEL,
            "prompt": "Reply with exactly one short word: working",
            "stream": False,
        },
        timeout=60,
    )
    print("HTTP status:", gen_response.status_code)
    print("Response body:")
    print(gen_response.text)
    if gen_response.status_code >= 400:
        print("Generation FAILED: the model is missing or not loaded.")
    else:
        result = gen_response.json()
        print("Raw JSON response:")
        print(json.dumps(result, indent=2))
        print("\nModel output:")
        print(result.get("response", ""))
except Exception as e:
    print("Generation FAILED")
    print(type(e).__name__, e)

Checking Ollama server...
Server status: OK
Installed models:
{
  "models": []
}

Testing generation...
HTTP status: 404
Generation FAILED
HTTPError 404 Client Error: Not Found for url: http://localhost:11434/api/generate

In [24]:
llama_results_df

,model_name,ai_text,reference_metaphor,predicted_metaphor,latency_seconds,cost_usd,error
0,llama3.1:8b,AI makes fewer medical mistakes,tool,ERROR,None,0.0,"HTTPConnectionPool(host='localhost', port=1143..."
1,llama3.1:8b,AI brings back people to life. Basically we ca...,tool,ERROR,None,0.0,"HTTPConnectionPool(host='localhost', port=1143..."
2,llama3.1:8b,genie in a bottle - you can ask it to do anyth...,genie,ERROR,None,0.0,"HTTPConnectionPool(host='localhost', port=1143..."
3,llama3.1:8b,Artificial intelligence is a tool that humans ...,tool,ERROR,None,0.0,"HTTPConnectionPool(host='localhost', port=1143..."
4,llama3.1:8b,AI is like making a cake from a box instead of...,tool,ERROR,None,0.0,"HTTPConnectionPool(host='localhost', port=1143..."
...,...,...,...,...,...,...,...
33171,qwen2,AI is like a teenage boy because you never kno...,child,ERROR,None,0.0,"HTTPConnectionPool(host='localhost', port=1143..."
33172,qwen2,AI is like A personal concierge. because It wi...,assistant,ERROR,None,0.0,"HTTPConnectionPool(host='localhost', port=1143..."
33173,qwen2,AI is like My goto because AI is my go to for....,tool,ERROR,None,0.0,"HTTPConnectionPool(host='localhost', port=1143..."
33174,qwen2,AI is like an personal assistant . because it ...,assistant,ERROR,None,0.0,"HTTPConnectionPool(host='localhost', port=1143..."
33175,qwen2,AI is like having a friend that does everythin...,assistant,ERROR,None,0.0,"HTTPConnectionPool(host='localhost', port=1143..."